<?php

$title = 'kBudget - Internetowy menadżer finansów';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    
    <p>
        kBudget jest internetowym menadżerem finansów. Serwis pozwala użytkownikowi na rejestrowanie jego
        transakcji, a następnie umożliwia wygenerowanie analizy wydatków i przychodów w postaci wykresów
        czasowych, bilansu oraz wykresów kołowych prezentujących to na co wydajemy najwięcej pieniędy.<br />
        <br />
        Poniżej przedstawione zostały przykładowe wykresy:
    </p>
    
    <!-- Lewy obrazek -->
    <div class="exampleChart">
        <img src="images/example_charts/category1.png" alt="Wykres2" title="Wykres kołowy" />
    </div>
        
    <!-- Prawy obrazek -->
    <div class="exampleChart">
        <img src="images/example_charts/time1.png" alt="Wykres1" title="Wykres czasowy" />
    </div>
    
    <p>
        Serwis jest całkowicie darmowy i może z niego korzystać każdy. Wystarczy się
        <a href="<?php echo $this->url('user/register');?>">zarejsetrować</a>.<br />
        Do rejestracji wymagane jest podanie loginu oraz adresu e-mail. Adres e-mail jest wykorzystywany do
        odzyskiwania hasła, w przypadku gdy użytkownik je zapomni.
    </p>

</div>
