<?php

$title = 'Dodaj transakcję';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Typ transakcji -->
<div class="span-24">
<p>
    Typ transakcji: <b><?php echo ($t_type==0)?('Przychód'):('Wydatek'); ?></b>
</p>
</div>

<div class="span-24">&nbsp;</div>

<!-- Formularz transakcji -->
<div class="span-24">
    
    <div class="transaction-form">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('transaction-add', array('type' => $t_type)));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('tid'));
        echo $this->formHidden($form->get('t_type'));
        echo $this->formRow($form->get('cid')).'<br />';
        echo $this->formRow($form->get('c_name')).'<br />';
        echo $this->formRow($form->get('t_date')).'<br />';
        echo $this->formRow($form->get('t_content')).'<br />';
        echo $this->formRow($form->get('t_value')).'<br />';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); 
        ?>
    </div>

</div>