<?php

$title = 'Edycja transakcji';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Typ transakcji -->
<div class="span-24">
<p>
    Typ transakcji: <b><?php echo ($t_type==0)?('Przychód'):('Wydatek'); ?></b>
</p>
</div>

<div class="span-24">&nbsp;</div>

<!-- Formularz transakcji -->
<div class="span-24">

    <div class="transaction-form">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('transaction-edit', array(
                                                                           'month'=>$dt['month'],
                                                                           'year'=>$dt['year'],
                                                                           'tid' => $this->tid,
                                                                           'page' => $this->page,
                                                                           )));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('tid'));
        echo $this->formHidden($form->get('t_type'));
        echo $this->formRow($form->get('cid')).'<br />';
        echo $this->formRow($form->get('c_name')).'<br />';
        echo $this->formRow($form->get('t_date')).'<br />';
        echo $this->formRow($form->get('t_content')).'<br />';
        echo $this->formRow($form->get('t_value')).'<br />';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); 
        ?>
    </div>

</div>

<div class="span-24">&nbsp;</div>

<div class="span-24">
    
    <p>
        <a href="<?php echo $this->url('transaction',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'page' => $this->page,
                        ));?>">Powrót</a>
    </p>
    
</div>