<?php

$title = 'Edycja transakcji';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Typ transakcji -->
<div class="span-24">
<p>
    Typ transakcji: <b><?php echo ($t_type==0)?('Przychód'):('Wydatek'); ?></b>
</p>
</div>

<div class="span-24">&nbsp;</div>

<!-- Formularz transakcji -->
<div class="span-24">

    <div class="transaction-form">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('transaction/edit', array(
                                                                           'month'=>$dt['month'],
                                                                           'year'=>$dt['year'],
                                                                           'tid' => $this->tid,
                                                                           'page' => $this->page,
                                                                           )));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        ?>
        
        <table class="TableClear">
            <tr>
                <td colspan="2"><?php echo $this->formHidden($form->get('tid')); ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->formHidden($form->get('t_type')); ?></td>
            </tr>
            <tr>
                <td><?php echo $form->get('cid')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('cid')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</tr>')
                    ->render($form->get('cid'));
            ?>
            <tr>
                <td><?php echo $form->get('c_name')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('c_name')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</tr>')
                    ->render($form->get('c_name'));
            ?>
            <tr>
                <td><?php echo $form->get('t_date')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('t_date')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</tr>')
                    ->render($form->get('t_date'));
            ?>
            <tr>
                <td><?php echo $form->get('t_content')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('t_content')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</tr>')
                    ->render($form->get('t_content'));
            ?>
            <tr>
                <td><?php echo $form->get('t_value')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('t_value')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</tr>')
                    ->render($form->get('t_value'));
            ?>
            <tr>
                <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
            </tr>
        </table>
        
        <?php $this->form()->closeTag(); ?>
        
    </div>

</div>

<div class="span-24">&nbsp;</div>

<div class="span-24">
    
    <p>
        <a href="<?php echo $this->url('transactions',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'page' => $this->page,
                        ));?>">Powrót</a>
    </p>
    
</div>