<?php

$title = 'kBudget - Transakcje';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Knefle dodające transakcje -->
<div class="row">
<div class="span12">

<div class="btn-group">
    <a href="<?php echo $this->url('transaction/add',
            array('type'=>0));?>" class="btn btn-success">Dodaj przychód</a>
            
    <a href="<?php echo $this->url('transaction/add',
            array('type'=>1));?>" class="btn btn-danger">Dodaj wydatek</a>
            
    <a href="<?php echo $this->url('import');?>" class="btn btn-info">Importuj wyciąg</a>
</div>
    
</div>
</div>

<br />

<div class="row">
<!-- Filtracja (lewa strona) -->
<div class="span6">
    <div class="FilterBox">
    Filtracja:
    <?php
    
    $form = $this->formRange;
    $form->setAttribute('action', $this->url('transaction/filter'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr>
            <td><?php echo $form->get('month')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('month')); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->get('year')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('year')); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>
    <?php
    
    echo $this->form()->closeTag();
    
    ?>
    </div>
</div>

<!-- Bilans (prawa strona) -->
<div class="span3">
    <table class="table table-striped">
        <tr>
            <td colspan="2" style="text-align: center;"><b>Bilans miesięczny</b></td>
        </tr>
        <tr>
            <td><div class="profit">Przychód</div></td>
            <td>+<?php echo $sum_profit; ?>zł</td>
        </tr>
        <tr>
            <td><div class="expense">Wydatki</div></td>
            <td>-<?php echo $sum_expense; ?>zł</td>
        </tr>
        <tr>
            <td><b>Oszczędności</b></td>
            <td><?php echo $balance; ?>zł</td>
        </tr>
    </table>
</div>

</div>

<div class="row">
<!-- Transakcje -->
<div class="span12">
    
<p>Twoje transakcje:</p>

    <?php if (count($transactions)) : ?>
    <table class="table table-bordered">
    <tr>
        <th>Typ</th>
        <th>data</th>
        <th>wartość</th>
        <th>opis</th>
        <th>kategoria</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($transactions as $transaction) : ?>
    <tr>
        <?php if ($transaction->t_type==0): ?>
        <td><div class="label label-success">Przychód</div></td>
        <?php else: ?>
        <td><div class="label label-important">Wydatek</div></td>
        <?php endif; ?>
        <td><?php echo $this->escapeHtml($transaction->t_date);?></td>
        <td><?php echo (($transaction->t_type==0)?('+'):('-')).$this->escapeHtml($transaction->t_value);?>zł</td>
        <td><?php echo $this->escapeHtml($transaction->t_content);?></td>
        <td><?php echo $this->escapeHtml($transaction->c_name);?></td>
        <td>
            <a href="<?php echo $this->url('transaction/edit',
                array(
                    'month'=>$dt['month'],
                    'year'=>$dt['year'],
                    'tid' => $transaction->tid,
                    'page' => $this->page,
                    ));?>">Edit</a>
            <a href="<?php echo $this->url('transaction/delete',
                array(
                    'month'=>$dt['month'],
                    'year'=>$dt['year'],
                    'tid' => $transaction->tid,
                    'page' => $this->page,
                    ));?>">Usuń</a>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    <?php else: ?>
    <p>Brak transakcji!</p>
    <?php endif; ?>

<p>
    <?php echo $this->paginationControl($this->transactions,
                                    'Sliding',
                                    'budget/paginator_control.phtml', array('AddrParams' => array(
                                                                                            'month' => $dt['month'],
                                                                                            'year' => $dt['year'],
                                                                                        )
                                                                                    )); ?>
</p>

</div>

</div>