<?php

$title = 'kBudget - Transakcje';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath('/css/transaction-list.css'));

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Knefle dodające transakcje -->
<div class="row">
<div class="span12">

<div class="btn-group">
    <a href="<?php echo $this->url('transaction/add',
            array('type'=>0, 'aid'=>$this->aid));?>" class="btn btn-success">Dodaj przychód</a>
            
    <a href="<?php echo $this->url('transaction/add',
            array('type'=>1, 'aid'=>$this->aid));?>" class="btn btn-danger">Dodaj wydatek</a>
            
    <a href="<?php echo $this->url('transaction/transfer-add',
            array('aid'=>$this->aid));?>" class="btn btn-warning">Transfer</a>
            
    <a href="<?php echo $this->url('import');?>" class="btn btn-info">Importuj wyciąg</a>
</div>

<div class="btn-group">
    <a href="<?php echo $this->url('analysis/time/month',
                array('aid'=>$this->aid, 'month'=>$this->dt['month'], 'year'=>$this->dt['year']));?>" class="btn">Analiza czasowa</a>
    <a href="<?php echo $this->url('analysis/category/month',
                array('aid'=>$this->aid, 'month'=>$this->dt['month'], 'year'=>$this->dt['year']));?>" class="btn">Analiza z podziałem na kategorie</a>
</div>

</div>
</div>

<br />

<div class="row">
<!-- Filtracja (lewa strona) -->
<div class="span6">
    <div class="FilterBox">
    Filtracja:
    <?php
    
    $form = $this->formRange;
    $form->setAttribute('action', $this->url('transaction/filter'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr>
            <td><?php echo $form->get('aid')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('aid')); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->get('month')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('month')); ?></td>
        </tr>
        <tr>
            <td><?php echo $form->get('year')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('year')); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>
    <?php
    
    echo $this->form()->closeTag();
    
    ?>
    </div>
</div>

<!-- Saldo na koncie (prawa strona) -->
<div class="span3">
    <table class="table table-striped">
        <tr>
            <td class="account-header">Aktualny stan konta</td>
        </tr>
        <tr>
            <td class="account-balance">
            <?php if ($this->accountBalance >= 0) : ?>
            <div class="balance-profit"><?php echo '+'.$this->accountBalance; ?>zł</div>
            <?php else: ?>
            <div class="balance-loss"><?php echo $this->accountBalance; ?>zł</div>
            <?php endif;?>
            </td>
        </tr>
    </table>
</div>

<!-- Bilans miesięczny (prawa strona) -->
<div class="span3">
    <table class="table table-striped">
        <tr>
            <td colspan="2" class="account-header">Bilans miesięczny</td>
        </tr>
        <tr>
            <td><div class="profit">Przychód</div></td>
            <td>+<?php echo $this->sum_profit; ?>zł</td>
        </tr>
        <tr>
            <td><div class="expense">Wydatki</div></td>
            <td>-<?php echo $this->sum_expense; ?>zł</td>
        </tr>
        <tr>
            <td><b>Oszczędności</b></td>
            <td>
            <?php if ($this->monthBalance >= 0) : ?>
            <div class="balance-profit"><?php echo '+'.$this->monthBalance; ?>zł</div>
            <?php else: ?>
            <div class="balance-loss"><?php echo $this->monthBalance; ?>zł</div>
            <?php endif;?>
            </td>
        </tr>
    </table>
</div>

</div>

<div class="row">
<!-- Transakcje -->
<div class="span12">
    
<p>Twoje transakcje:</p>

    <?php if (count($this->transactions)) : ?>
    <table class="table table-bordered">
    <tr>
        <th>Typ</th>
        <th>data</th>
        <th>wartość</th>
        <th>opis</th>
        <th>kategoria</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->transactions as $transaction) : ?>
    <tr>
        <?php if ($transaction->t_type==0): ?>
        <td><div class="label label-success">Przychód</div></td>
        <?php elseif ($transaction->t_type==1): ?>
        <td><div class="label label-important">Wydatek</div></td>
        <?php else: ?>
        <td><div class="label label-warning">Transfer</div></td>
        <?php endif; ?>
        <td><?php echo $this->escapeHtml($transaction->t_date);?></td>
        <td><?php echo (($transaction->t_type==0||$transaction->t_type==3)?('+'):('-')).$this->escapeHtml($transaction->t_value);?>zł</td>
        <td><?php echo $this->escapeHtml($transaction->t_content);?></td>
        <td>
        <?php 
        if ($transaction->t_type==0 || $transaction->t_type==1) {
            $cat = $this->categories[$transaction->tid];

            if ($cat[1] === null) { // Main category
            
                echo $this->escapeHtml($cat[0]);
            
            } else { // Main category + subcategory
            
                echo $this->escapeHtml($cat[0].' -> '.$cat[1]);
            
            }
        } else if ($transaction->t_type==2) { // Outgoing transfer

            echo 'Transfer do: '.$this->accountsNames[$transaction->taid];

        } else if ($transaction->t_type==3) { // Incoming transfer

            echo 'Transfer z: '.$this->accountsNames[$transaction->taid];

        }
        
        
        ?>
        </td>
        <td>
            <?php if ($transaction->t_type==0 || $transaction->t_type==1): ?>
                <a href="<?php echo $this->url('transaction/edit',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'tid' => $transaction->tid,
                        'page' => $this->page,
                        ));?>">Edit</a>
                <a href="<?php echo $this->url('transaction/delete',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'tid' => $transaction->tid,
                        'page' => $this->page,
                        ));?>">Usuń</a>
            <?php else: ?>
                <a href="<?php echo $this->url('transaction/transfer-edit',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'tid' => $transaction->tid,
                        'aid' => $this->aid,
                        'page' => $this->page,
                        ));?>">Edit</a>
                <a href="<?php echo $this->url('transaction/transfer-delete',
                    array(
                        'month'=>$dt['month'],
                        'year'=>$dt['year'],
                        'tid' => $transaction->tid,
                        'page' => $this->page,
                        ));?>">Usuń</a>
            <?php endif;?>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    <?php else: ?>
    <p>Brak transakcji!</p>
    <?php endif; ?>

<p>
    <?php echo $this->paginationControl($this->transactions,
                                    'Sliding',
                                    'base/paginator_control.phtml', array('AddrParams' => array(
                                                                                            'aid' => $this->aid,
                                                                                            'month' => $dt['month'],
                                                                                            'year' => $dt['year'],
                                                                                        )
                                                                                    )); ?>
</p>

</div>

</div>
