<?php

$title = 'Transfer środków';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Formularz transferu -->
<div class="row">
    
    <div class="span12">
    
    <?php if (!$this->ERR): ?>
    
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('transaction/transfer-add', array(
                                                                    'aid' => $this->aid
                                                                    )));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        ?>
        
        <table class="TableClear">
            <tr>
                <td><?php echo $form->get('accountId')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('accountId')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</td></tr>')
                    ->render($form->get('accountId'));
            ?>
            <tr>
                <td><?php echo $form->get('transferAccountId')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('transferAccountId')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</td></tr>')
                    ->render($form->get('transferAccountId'));
            ?>
            <tr>
                <td><?php echo $form->get('date')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('date')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</td></tr>')
                    ->render($form->get('date'));
            ?>
            <tr>
                <td><?php echo $form->get('content')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('content')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</td></tr>')
                    ->render($form->get('content'));
            ?>
            <tr>
                <td><?php echo $form->get('value')->getLabel(); ?></td>
                <td><?php echo $this->formElement($form->get('value')) ?></td>
            </tr>
            <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<tr><td colspan="2">')
                    ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                    ->setMessageCloseString('</td></tr>')
                    ->render($form->get('value'));
            ?>
            <tr>
                <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
            </tr>
        </table>
        
        <?php $this->form()->closeTag(); ?>
        
    <?php else: ?>
            
        <div class="alert alert-warning">
            W systemie istnieje tylko jedno konto bankowe.<br />
            Dodaj nowe konto bankowe w ustawieniach, a następnie spróbuj ponownie.
        </div>
        <a href="<?php echo $this->url('transactions');?>">Powrót</a>
            
    <?php endif; ?>
        
    </div>

</div>
