<?php

$title = 'kBudget - Administracja użytkownikami';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="span-24">&nbsp;</div>

<!-- Lista userów -->
<div class="span-24">
    
    <?php if (count($this->users)==0): ?>
    <p>Brak użytkowników w systemie!</p>
    <?php else: ?>
    <table>
    <tr>
        <th>uid</th>
        <th>login</th>
        <th>e-mail</th>
        <th>Typ</th>
        <th>Stan</th>
        <th>Data rejestracji</th>
        <th>Data ostatniego logowania</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->users as $user) : ?>
    <tr>
        <td><?php echo $user->uid; ?></td>
        <td><?php echo $this->escapeHtml($user->login); ?></td>
        <td><?php echo $this->escapeHtml($user->email); ?></td>
        <td><?php echo ($user->u_type==1)?('Administrator'):('Użytkownik'); ?></td>
        <td>
        <?php if ($user->active==0): ?>
        <a href="<?php echo $this->url('admin-user-activate', array(
                                                                    'uid' => $user->uid,
                                                                    'active' => 1,
                                                                    'page' => $this->page,
                                                            ));?>"><div style="color: red;">Nieaktywny</div></a>
        <?php elseif ($user->active==1): ?>
        <a href="<?php echo $this->url('admin-user-activate', array(
                                                                    'uid' => $user->uid,
                                                                    'active' => 0,
                                                                    'page' => $this->page,
                                                            ));?>"><div style="color: green;">Aktywny</div></a>
        <?php endif; ?>
        </td>
        <td><?php echo $this->escapeHtml($user->register_date); ?></td>
        <td><?php echo $this->escapeHtml($user->last_login_date); ?></td>
        <td>
            <a href="<?php echo $this->url('admin-user-pass', array(
                                                                    'uid' => $user->uid,
                                                                    'page' => $this->page,
                                                            ));?>">Zmień hasło</a>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    <?php endif; ?>
    
</div>

<div class="span-24">&nbsp;</div>

<!-- Sterowanie stronami -->
<div class="span-24">
    <?php echo $this->paginationControl($this->users,
                                    'Sliding',
                                    'budget/paginator_control.phtml'); ?>
</div>