<script type="text/javascript">
$(function () {
    
    var categories = [
                    <?php foreach ($this->chartData as $key=>$value): ?>
                    <?= "'".$key."'"; ?>,
                    <?php endforeach; ?>
                    ],
        data = [
                <?php foreach ($this->chartData as $key=>$value): ?>
                {
                    name : <?= "'".$key."'"; ?>,
                    y: <?= $value['value']; ?>,
                    <?php if (isset($value['drilldown'])): ?>
                    drilldown: {
                        name: <?= "'".$key."'"; ?>,
                        data: [
                                <?php foreach ($value['drilldown'] as $skey=>$svalue): ?>
                                [<?= "'".$skey."'"; ?>,<?= $svalue; ?>],
                                <?php endforeach; ?>
                            ]
                    }
                    <?php endif; ?>
                },
                <?php endforeach; ?>
                ];

    function setChart(chart, name, categories, data) {
        chart.xAxis[0].setCategories(categories);
        chart.series[0].remove();
        chart.addSeries({
            name: name,
            data: data
        });
    }

    var chart = new Highcharts.Chart({
        chart: {
            renderTo: <?= "'".$this->chartId."'"; ?>,
            type: 'pie'
        },
        title: {
            text: <?= "'".$this->chartTitle."'"; ?>
        },
        subtitle: {
            text: <?= "'".$this->chartSubtitle."'"; ?>
        },
        xAxis: {
            categories: categories
        },
        plotOptions: {
            pie: {
                cursor: 'pointer',
                point: {
                    events: {
                        click: function() {
                            var drilldown = this.drilldown;
                            if (drilldown) { // drill down
                                chart.setTitle({text: chart.title.text},
                                    {text: <?= "'".$this->chartSubtitle."'"; ?> + '<br />Główna kategoria: '+drilldown.name}
                                );
                                setChart(chart, drilldown.name, drilldown.categories, drilldown.data);
                            } else { // restore
                                chart.setTitle({text: chart.title.text},
                                    {text: <?= "'".$this->chartSubtitle."'"; ?>}
                                );
                                setChart(chart, name, categories, data);
                            }
                        }
                    }
                },
                dataLabels: {
                    enabled: true,
                    style: {
                        fontWeight: 'bold'
                    },
                    formatter: function() {
                        return this.point.name +'<br>' + this.y + <?= "'".$this->dataUnit."'"; ?> + ' ('+this.percentage.toFixed(2)+' %)' ;
                    }
                }
            }
        },
        tooltip: {
            formatter: function() {
                var point = this.point;
                var s = '<b>'+ point.name +'</b>: '+this.y+<?= "'".$this->dataUnit."'"; ?>;
                
                return s;
            }
        },
        series: [{
            name: name,
            data: data,
            color: 'white'
        }],
        exporting: {
            enabled: false
        }
    });
});
</script>

<div id="<?= $this->chartId; ?>" style="min-width: <?= $this->chartWidth; ?>px; height: <?= $this->chartHeight; ?>px; margin: 0 auto"></div>
