<?php

$title = 'kBudget - Edycja kategorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<div class="span-24">
<p>
    <a href="<?php echo $this->url('configuration-category');?>">Ustawienia kategorii</a>
    <a href="<?php echo $this->url('configuration-email');?>">Zmiana adresu e-mail</a>
    <a href="<?php echo $this->url('configuration-pass');?>">Zmiana hasła</a>
</p>
</div>

<div class="span-24">&nbsp;</div>

<!-- Formularz kategorii -->
<div class="span-12 last">
    <div class="AddCategoryBox">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('configuration-category-edit', array(
                                                                    'cid' => $cid,
                                                                    )));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('cid'));
        echo $this->formHidden($form->get('c_type'));
        echo $this->formRow($form->get('c_name')).'<br />';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); 
        ?>
    </div>
</div>

<div class="span-24">
    <p>
    <a href="<?php echo $this->url('configuration-category');?>">Powrót</a>
    </p>
</div>