<?php

$title = 'kBudget - Zmiana hasła';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<div class="span-24">
<p>
    <a href="<?php echo $this->url('configuration-category');?>">Ustawienia kategorii</a>
    <a href="<?php echo $this->url('configuration-email');?>">Zmiana adresu e-mail</a>
    <a href="<?php echo $this->url('configuration-pass');?>">Zmiana hasła</a>
</p>
</div>

<div class="span-24">&nbsp;</div>

<div class="span-24">

    <?php if ($ERR==1): ?>
    <div class="error" style="width: 30%;">
        Aktualne hasło jest inne!
    </div>
    <?php elseif ($ERR==2): ?>
    <div class="error" style="width: 30%;">
        Podane nowe hasła nie są zgodne!
    </div>
    <?php elseif ($ERR==3): ?>
    <div class="success" style="width: 30%;">
        Hasło zostało zmienione!
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('configuration-pass'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('pass')).'<br />';
    echo $this->formRow($form->get('pass1')).'<br />';
    echo $this->formRow($form->get('pass2')).'<br />';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag(); 
    ?>

</div>