<?php

$title = 'kBudget - Zmiana hasła';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<?php echo $this->configMenu() ?>

<br />

<div class="row">
    <div class="span12">
    <?php if ($ERR==1): ?>
    <div class="alert alert-error" style="width: 30%;">
        Aktualne hasło jest inne!
    </div>
    <?php elseif ($ERR==2): ?>
    <div class="alert alert-error" style="width: 30%;">
        Podane nowe hasła nie są zgodne!
    </div>
    <?php elseif ($ERR==3): ?>
    <div class="alert alert-success" style="width: 30%;">
        Hasło zostało zmienione!
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user/pass'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    
    <table>
        <tr>
            <td><b><?php echo $form->get('pass')->getLabel(); ?></b></td>
            <td><?php echo $this->formElement($form->get('pass')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass'));
        ?>
        <tr>
            <td><b><?php echo $form->get('pass1')->getLabel(); ?></b></td>
            <td><?php echo $this->formElement($form->get('pass1')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass1'));
        ?>
        <tr>
            <td><b><?php echo $form->get('pass2')->getLabel(); ?></b></td>
            <td><?php echo $this->formElement($form->get('pass2')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass2'));
        ?>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>
    
    <?php $this->form()->closeTag(); ?>
    </div>
</div>