<?php

$title = 'Odzyskiwanie hasła';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="span-24">
    
    <?php if ($this->CONFIRM) : ?>
    
    <div class="success" style="width: 50%;">
        Hasło zostało zresetowane. Nowe hasło otrzymasz na podany adres e-mail.
    </div>
    
    <?php else: ?>
    
    <div class="notice">
    Aby odzyskać hasło proszę podać adres e-mail, który podawano podczas rejestracji w serwisie.
    </div>
    
    <?php if ($this->ERR==1) : ?>
    <div class="error" style="width: 30%;">
        Podany adres e-mail nie istnieje w naszej bazie!
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user/passrst'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    
    <table class="TableClear">
        <tr>
            <td><?php echo $form->get('email')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('email')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2">')
                ->setMessageSeparatorString('</td></tr><tr><td colspan="2">')
                ->setMessageCloseString('</tr>')
                ->render($form->get('email'));
        ?>
        <tr>
            <td colspan="2"><?php echo $this->formHidden($form->get('csrf')); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>
    
    <?php $this->form()->closeTag(); ?>
    
    <?php endif; ?>

</div>
