<?php

$title = 'Rejestracja nowego użytkownika';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="span12">
    
    <?php if ($this->CONFIRM) : ?>
    
    <div class="alert alert-success">
        Rejestracja została wykonana poprawnie.<br />
        Teraz możesz się <a href="<?php echo $this->url('user/login');?>">zalogować</a> na Swoje konto.
    </div>
    
    <?php else: ?>
    
    <div class="alert alert-info">
    Proszę wypełnić poniższe pola. Każdy z elementów formularza jest wymagany do rejestracji!
    </div>
    
    <?php if ($this->ERR==1) : ?>
    <!-- Błąd podczas rejestracji -->
    <div class="alert alert-error" style="width: 30%;">
        Podany login już istnieje.
    </div>
    <?php elseif ($this->ERR==2) : ?>
    <div class="alert alert-error" style="width: 30%;">
        Podany e-mail istnieje w bazie danych.
    </div>
    <?php elseif ($this->ERR==3) : ?>
    <div class="alert alert-error" style="width: 30%;">
        Podane hasła są niezgodne!
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user/register'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    
    <table>
        <tr>
            <td><?php echo $form->get('login')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('login')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('login'));
        ?>
        <tr>
            <td><?php echo $form->get('bankAccount')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('bankAccount')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('bankAccount'));
        ?>
        <tr>
            <td><?php echo $form->get('email')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('email')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('email'));
        ?>
        <tr>
            <td><?php echo $form->get('pass1')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('pass1')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass1'));
        ?>
        <tr>
            <td><?php echo $form->get('pass2')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('pass2')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass2'));
        ?>
        <tr>
            <td><?php echo $form->get('captcha')->getLabel(); ?></td>
            <td><?php echo $this->formElement($form->get('captcha')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('captcha'));
        ?>
        <tr>
            <td colspan="2"><?php echo $this->formHidden($form->get('csrf')); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>
    
    <?php $this->form()->closeTag(); ?>
    
    <?php endif; ?>

    </div>
</div>
