<?php

$title = 'Logowanie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="span-24">
    
    <?php if ($this->ERR) : ?>
    <div class="error" style="width: 30%;">
        Błąd podczas logowania.
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user-login'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('login')).'<br />';
    echo $this->formRow($form->get('pass')).'<br />';
    echo $this->formHidden($form->get('csrf'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    
    ?>
    
</div>

<div class="span-24">&nbsp;</div>

<div class="span-24">
    <p>
        Nie pamiętasz hasła? <a href="<?php echo $this->url('user-passrst');?>">Odzyskiwanie</a> hasła.
    </p>
</div>
