<?php

$title = 'Odzyskiwanie hasła';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="span-24">
    
    <?php if ($this->CONFIRM) : ?>
    
    <div class="success" style="width: 50%;">
        Hasło zostało zresetowane. Nowe hasło otrzymasz na podany adres e-mail.
    </div>
    
    <?php else: ?>
    
    <?php if ($this->ERR==1) : ?>
    <div class="error" style="width: 30%;">
        Podany adres e-mail nie istnieje w naszej bazie!
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user-passrst'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('email')).'<br />';
    echo $this->formHidden($form->get('csrf'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
    
    <?php endif; ?>

</div>
