<div class="row">
<div class="span12">

<div class="btn-group">
  <a href="<?php echo $this->url('user/category');?>" class="btn">Ustawienia kategorii</a>
  <a href="<?php echo $this->url('user/account');?>" class="btn">Konta bankowe</a>
  <a href="<?php echo $this->url('user/email');?>" class="btn">Zmiana adresu e-mail</a>
  <a href="<?php echo $this->url('user/pass');?>" class="btn">Zmiana hasła</a>
</div>

</div>
</div>