<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Analiza domowego budżetu'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- CSS -->
        <link rel="stylesheet" href="/css/bootstrap/bootstrap.css" type="text/css">
        <link rel="stylesheet" href="/css/style.css" type="text/css">
        <?php echo $this->headLink(); ?>

        <!-- Scripts -->
        <?php 
        
        echo $this->headScript()->prependFile($this->basePath('/js/jquery-1.9.1.min.js'))
                            ->prependFile($this->basePath('/js/bootstrap/bootstrap.min.js'))
        
        ?>
        
    </head>
    <body>
    <!-- Menu -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<?php echo $this->url('main');?>">kBudget</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <?php echo $this->userMenu(); ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
        <div class="container">
            
            <!-- Treść -->
            <div class="row">
                
                <?php echo $this->content; ?>
                
            </div>
            <!-- /Treść -->
            
            <br />
            
            <div class="row">
                <div style="text-align: center;">
                    <footer>
                        <p>Copyright &copy; 2013 by Mateusz Mirosławski</p>
                    </footer>
                </div>
            </div>
            <?php echo $this->inlineScript() ?>
        
        </div>
        
    </body>
</html>
