<?php

$title = 'kBudget - Analiza transakcji z podziałem na kategorie';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath('/css/analysis.css'));
$this->headScript()->prependFile($this->basePath('/js/app/analysis/filterForm.js'));
$this->headScript()->prependFile($this->basePath('/js/highcharts/highcharts.js'));
$this->headScript()->prependFile($this->basePath('/js/highcharts/modules/exporting.js'));

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
<div class="span12">
    <a href="<?php echo $this->url('analysis');?>">Powrót</a>
</div>
</div>

<br />

<!-- Filtering -->
<div class="row">
    <div class="span12">
        
        <?= $this->filterForm($this->form, 'analysis/category'); ?>

    </div>
</div>

<br />

<div class="row">
    <div class="span12">
        <a href="<?php echo $this->url('analysis/category');?>">Wyświetl aktualny miesiąc</a>
    </div>
</div>

<!-- Expenses -->
<div class="row">

    <div class="span12">
        <?php if (!empty($this->expenseData)): ?>
            <?= $this->pieChart('pieExpenses', 'Wykres kołowy wydatków', $this->subtitle, 'zł', 300, 400, $this->expenseData); ?>
        <?php else: ?>
            Brak wydatków w wybranym okresie!
        <?php endif; ?>
    </div>

</div>

<!-- Incomes -->
<div class="row">

    <div class="span12">
        <?php if (!empty($this->profitData)): ?>
            <?= $this->pieChart('pieProfits', 'Wykres kołowy przychodów', $this->subtitle, 'zł', 300, 400, $this->profitData); ?>
        <?php else: ?>
            Brak przychodów w wybranym okresie!
        <?php endif; ?>
    </div>

</div>
