<?php

$title = 'kBudget - Analiza czasowa transakcji';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<script language="javascript">
 
function Zakryj() {
    if ($('#filter_type').val()=='between') {
        $('#month_filter').hide();
        $('#between_filter').show();
    } else if ($('#filter_type').val()=='all') {
        $('#month_filter').hide();
        $('#between_filter').hide();
    } else {
        $('#month_filter').show();
        $('#between_filter').hide();
    }
};
 
// Załadowanie dokumentu
$(document).ready(function(){
    
    // Domyślne formatki
    Zakryj();
    
    // Zmieniono selekta od typu filtracji
    $('#filter_type').change(function(){
        if ($('option:selected', this).val() == 'month') {
            $('#month_filter').show();
            $('#between_filter').hide();
        }
        if ($('option:selected', this).val() == 'between') {
            $('#month_filter').hide();
            $('#between_filter').show();
        }
        if ($('option:selected', this).val() == 'all') {
            $('#month_filter').hide();
            $('#between_filter').hide();
        }
    });
 
});
</script>

<div class="span-24">
<p>
    <a href="<?php echo $this->url('analysis');?>">Powrót</a>
</p>
</div>

<!-- Filtracja -->
<div class="span-24">
    <div class="FilterBox">
        
        <p>Filtracja:</p>
        
        <?php
        
        $form = $this->form;
        $form->setAttribute('action', $this->url('analysis-time'));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('filter_type')).'<br />';
        echo '<div id="month_filter">';
        echo $this->formRow($form->get('month')).'<br />';
        echo $this->formRow($form->get('year')).'<br />';
        echo '</div>';
        echo '<div id="between_filter">';
        echo $this->formRow($form->get('date_from')).'<br />';
        echo $this->formRow($form->get('date_to')).'<br />';
        echo '</div>';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        
        ?>

    </div>
</div>

<div class="span-24">&nbsp;</div>

<div class="span-24">
    <p>
        <a href="<?php echo $this->url('analysis-time');?>">Wyświetl aktualny miesiąc</a>
    </p>
</div>

<!-- Wykresy (lewa strona) -->
<div class="span-16">
    
    <img src="<?php echo $balance_chart; ?>" />
    
    <p>
        <?php if ($ONE_PROFIT): ?>
        <?php for ($i=0; $i<$ONE_PROFIT; $i++): ?>
            Przychody z dnia <?php echo $this->escapeHtml($dt_profit['labels'][$i]); ?>
            o wartości: <?php echo $this->escapeHtml($dt_profit['data'][$i]); ?>zł
            <br />
        <?php endfor; ?>
        <?php else: ?>
        
            <?php if ($time_profit_chart): ?>
            <img src="<?php echo $time_profit_chart; ?>" />
            <?php else: ?>
            Brak przychodów w wybranym miesiącu!
            <?php endif; ?>
            
        <?php endif; ?>
    </p>
    
    <p>
        <?php if ($ONE_EXPENSE): ?>
        <?php for ($i=0; $i<$ONE_EXPENSE; $i++): ?>
            Wydatki z dnia <?php echo $this->escapeHtml($dt_expense['labels'][$i]); ?>
            o wartości: <?php echo $this->escapeHtml($dt_expense['data'][$i]); ?>zł
            <br />
        <?php endfor; ?>
        <?php else: ?>
        
            <?php if ($time_expense_chart): ?>
            <img src="<?php echo $time_expense_chart; ?>" />
            <?php else: ?>
            Brak wydatków w wybranym miesiącu!
            <?php endif; ?>
            
        <?php endif; ?>
    </p>
    
</div>

<!-- Bilans (prawa strona) -->
<div class="span-6 last">

    <div class="transactions-box">
    
        <table>
            <tr>
                <td colspan="2" style="text-align: center;"><b>Bilans</b></td>
            </tr>
            <tr>
                <td><div class="profit">Przychód</div></td>
                <td>+<?php echo $sum_profit; ?>zł</td>
            </tr>
            <tr>
                <td><div class="expense">Wydatki</div></td>
                <td>-<?php echo $sum_expense; ?>zł</td>
            </tr>
            <tr>
                <td><b>Oszczędności</b></td>
                <td><?php echo $balance; ?>zł</td>
            </tr>
        </table>
        
    </div>
    
</div>
