<?php

$title = 'kBudget - Analiza czasowa transakcji';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath('/css/analysis.css'));
$this->headScript()->prependFile($this->basePath('/js/app/analysis/filterForm.js'));
$this->headScript()->prependFile($this->basePath('/js/highcharts/highcharts.js'));
$this->headScript()->prependFile($this->basePath('/js/highcharts/modules/exporting.js'));

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
<div class="span12">
    <a href="<?php echo $this->url('analysis');?>">Powrót</a>
</div>
</div>

<br />

<!-- Filtering -->
<div class="row">
    <div class="span12">
        
        <?= $this->filterForm($this->form, 'analysis/time'); ?>

    </div>
</div>

<br />

<div class="row">
    <div class="span12">
        <a href="<?php echo $this->url('analysis/time');?>">Wyświetl aktualny miesiąc</a>
    </div>
</div>

<div class="row">
<!-- Cherts (left side) -->
<div class="span9">

<div class="row">
<?= $this->balanceChart('balances', 'Suma transakcji', 'Suma', 'zł', 400, 180, $this->balanceData); ?>
</div>

<div class="row">
<?php if (count($this->profitData['data'])): ?>
<?= $this->xyChart('profits', 'Wykres czasowy przychodów', 'Przychody', 'zł', 400, 400, $this->profitData); ?>
<?php else: ?>
<div class="alert alert-error">
Brak przychodów w wybranym okresie!
</div>
<?php endif; ?>
</div>

<div class="row">
<?php if (count($this->expenseData['data'])): ?>
<?= $this->xyChart('expenses', 'Wykres czasowy wydatków', 'Wydatki', 'zł', 400, 400, $this->expenseData); ?>
<?php else: ?>
<div class="alert alert-success">
Brak wydatków w wybranym okresie!
</div>
<?php endif; ?>
</div>

</div>

<!-- Balance (right side) -->
<div class="span3">
    <table class="table table-striped">
        <tr>
            <td colspan="2" style="text-align: center;"><b>Bilans</b></td>
        </tr>
        <tr>
            <td><div class="profit">Przychody</div></td>
            <td>+<?= $this->balanceData['profits']; ?>zł</td>
        </tr>
        <tr>
            <td><div class="expense">Wydatki</div></td>
            <td>-<?= $this->balanceData['expenses']; ?>zł</td>
        </tr>
        <tr>
            <td><b>Oszczędności</b></td>
            <td><?= $this->balanceData['balance']; ?>zł</td>
        </tr>
    </table>
</div>
</div>
