<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Analiza domowego budżetu'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- CSS -->
        <link rel="stylesheet" href="css/blueprint/screen.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="css/blueprint/print.css" type="text/css" media="print"> 
        <!--[if lt IE 8]>
          <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
        <![endif]-->
        <link rel="stylesheet" href="/css/style.css" type="text/css">

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.9.0.min.js') ?>
        
    </head>
    <body>
        
        <div class="container">
        
            <!-- Menu -->
            <div class="span-24">
                <a href="<?php echo $this->url('main');?>"><div class="MenuItem">Start</div></a>
                <a href="<?php echo $this->url('transaction', array('month'=>(int)date('m'), 'year'=>(int)date('Y')));?>"><div class="MenuItem">Transakcje</div></a>
                <a href="<?php echo $this->url('analysis');?>"><div class="MenuItem">Analiza</div></a>
                <a href="<?php echo $this->url('configuration');?>"><div class="MenuItem">Ustawienia</div></a>
                <a href="<?php echo $this->url('user-register');?>"><div class="MenuItem">Zarejestruj nowego użytkownika</div></a>
                <?php if ($this->user_name != 'anonymous'): ?>
                <div class="UserInfo">
                Użytkownik: <b><?php echo $this->escapeHtml($this->user_name); ?></b>
                </div>
                <?php endif; ?>
                <a href="<?php echo $this->log_btn['url']; ?>"><div class="MenuItem"><?php echo $this->log_btn['title']; ?></div></a>
            </div>
            <hr />
            
            <!-- Treść -->
            <div  class="span-24">
                
                <?php echo $this->content; ?>
                
            </div>
            <!-- /Treść -->
            
            <div class="span-24">&nbsp;</div>
            
            <div class="span-24">
                <div style="text-align: center;">
                    <footer>
                        <p>Copyright &copy; 2013 by Mateusz Mirosławski.</p>
                    </footer>
                </div>
            </div>
            <?php echo $this->inlineScript() ?>
        
        </div>
        
    </body>
</html>
