<?php

$title = 'kBudget - Administracja użytkownikami';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">

<!-- Lista userów -->
<div class="span12">
    
    <?php if (count($this->users)==0): ?>
    Brak użytkowników w systemie!
    <?php else: ?>
    <table class="table table-bordered">
    <tr>
        <th>uid</th>
        <th>login</th>
        <th>e-mail</th>
        <th>Typ</th>
        <th>Stan</th>
        <th>Data rejestracji</th>
        <th>Data ostatniego logowania</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->users as $user) : ?>
    <tr>
        <td><?php echo $user->userId; ?></td>
        <td><?php echo $this->escapeHtml($user->login); ?></td>
        <td><?php echo $this->escapeHtml($user->email); ?></td>
        <td><?php 
        
        switch ($user->type) {
            case 0: echo '<span class="label">Użytkownik</span>'; break;
            case 1: echo '<span class="label label-important">Administrator</span>'; break;
            case 2: echo '<span class="label label-info">Demo</span>'; break;
        }
        
        ?></td>
        <td>
        <?php if ($user->active==0): ?>
        <a href="<?php echo $this->url('admin/users/activate', array(
                                                                    'uid' => $user->userId,
                                                                    'active' => 1,
                                                                    'page' => $this->page,
                                                            ));?>"><div style="color: red;">Nieaktywny</div></a>
        <?php elseif ($user->active==1): ?>
        <a href="<?php echo $this->url('admin/users/activate', array(
                                                                    'uid' => $user->userId,
                                                                    'active' => 0,
                                                                    'page' => $this->page,
                                                            ));?>"><div style="color: green;">Aktywny</div></a>
        <?php endif; ?>
        </td>
        <td><?php echo $this->escapeHtml($user->registerDate); ?></td>
        <td><?php echo $this->escapeHtml($user->lastLoginDate); ?></td>
        <td>
            <a href="<?php echo $this->url('admin/users/password', array(
                                                                    'uid' => $user->userId,
                                                                    'page' => $this->page,
                                                            ));?>">Zmień hasło</a>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    <?php endif; ?>
    
</div>

</div>

<div class="row">

    <!-- Sterowanie stronami -->
    <div class="span12">
        <?php echo $this->paginationControl($this->users,
                                        'Sliding',
                                        'base/paginator_control.phtml'); ?>
    </div>

</div>
