<?php

$title = 'kBudget - Zmiana hasła wybranego użytkownika';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="span12">

    <?php if ($ERR==2): ?>
    <div class="alert alert-error" style="width: 30%;">
        Nowe hasła nie są zgodne!
    </div>
    <?php elseif ($ERR==3): ?>
    <div class="alert alert-success" style="width: 30%;">
        Hasło zostało zmienione!
        <a href="<?php echo $this->url('admin/users/list', array(
                                                            'page' => $this->page,
                                                    ));?>">OK</a>
    </div>
    <?php endif; ?>
    
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin/users/password',array(
                                                                'uid' => $this->uid,
                                                                'page' => $this->page,
                                                            )));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    
    <table>
        <tr>
            <td><b><?php echo $form->get('pass1')->getLabel(); ?></b></td>
            <td><?php echo $this->formElement($form->get('pass1')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass1'));
        ?>
        <tr>
            <td><b><?php echo $form->get('pass2')->getLabel(); ?></b></td>
            <td><?php echo $this->formElement($form->get('pass2')) ?></td>
        </tr>
        <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
                ->setMessageCloseString('</div></td></tr>')
                ->render($form->get('pass2'));
        ?>
        <tr>
            <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
        </tr>
    </table>

    <?php echo $this->form()->closeTag(); ?>

    </div>
</div>