<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <?php if (isset($this->AddrParams)): ?>
  <a href="<?php echo $this->url($this->route, array_merge($this->AddrParams, array('page' => $this->previous))); ?>">
  <?php else: ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
  <?php endif; ?>
    < Poprzednia
  </a> |
<?php else: ?>
  <span class="disabled">< Poprzednia</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <?php if (isset($this->AddrParams)): ?>
    <a href="<?php echo $this->url($this->route, array_merge($this->AddrParams, array('page' => $page))); ?>">
    <?php else: ?>
    <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
    <?php endif; ?>
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <?php if (isset($this->AddrParams)): ?>
  <a href="<?php echo $this->url($this->route, array_merge($this->AddrParams, array('page' => $this->next))); ?>">
  <?php else: ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
  <?php endif; ?>
    Następna >
  </a>
<?php else: ?>
  <span class="disabled">Następna ></span>
<?php endif; ?>
</div>
<?php endif; ?>