<?php

$title = 'kBudget - Import wyciągu bankowego';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath('/css/import-transaction.css'));
$this->headScript()->prependFile($this->basePath('/js/app/import/transactionImport.js'));

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
<div class="span4">

    <div class="alert alert-info">
            Przetworzono <b><?php echo $this->TR_COUNTED; ?></b> z <b><?php echo $this->ALL_TR_COUNT; ?></b> transakcji.
    </div>

</div>

<div class="span8">
    <div id="catWait"><img alt="Czekaj..." src="/images/loading.gif"></div>
</div>
</div>

<div class="row">
<div class="span12">

<?php if ($this->ERR == 0) : ?>
    
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('import/commit'));
$form->prepare();
?>

<?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('trCount'));
?>
<table id="importTable">
    <tr>
        <th class="type">Typ</th>
        <th>Kategoria/Konto</th>
        <th>Data</th>
        <th>Opis</th>
        <th>Wartość</th>
        <th>Ignoruj</th>
    </tr>
    <?php for ($i=0; $i<$this->TR_COUNT; $i++): ?>
    <tr>
        <td>
        <?php
            echo $this->formElement($form->get('t_type-'.$i));
        ?>
        </td>
        <td>
            <!-- Categories -->
            <div id="categoryRow-<?= $i; ?>">
                <?php echo $this->formElement($form->get('pcid-'.$i)); ?><br />
                <div id="newMainCategoryRow-<?= $i;?>">
                    <?php echo $this->formElement($form->get('newMainCategoryName-'.$i)); ?><br />
                    <input type="button" id="submitNewCategory-<?= $i; ?>" value="Dodaj kategorię" class="submitCategory" />
                </div>
                
                <div id="subCategoryRow-<?= $i; ?>">
                    <?php echo $this->formElement($form->get('ccid-'.$i)); ?><br />
                    <div id="newSubCategoryRow-<?= $i;?>">
                    <?php echo $this->formElement($form->get('newSubCategoryName-'.$i)); ?><br />
                    <input type="button" id="submitNewSubCategory-<?= $i; ?>" value="Dodaj podkategorię" />
                    </div>
                </div>
            </div>
            <!-- Bank accounts -->
            <div id="accountRow-<?= $i; ?>">
            <?php echo $this->formElement($form->get('taid-'.$i)); ?>
            </div>
        
        </td>
        <td><?php echo $this->formElement($form->get('t_date-'.$i)); ?></td>
        <td><?php echo $this->formElement($form->get('t_content-'.$i)); ?></td>
        <td><?php echo $this->formElement($form->get('t_value-'.$i)); ?></td>
        <td><?php echo $this->formElement($form->get('ignore-'.$i)); ?></td>
    </tr>
    <?php endfor; ?>
</table>
<?php
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag(); 
?>

<a href="<?php echo $this->url('import/cancel');?>">Anuluj importowanie</a>
    
<?php else: ?>
    <div class="alert alert-error" style="width: 30%;">
        Wystąpił błąd podczas przetwarzania pliku!<br />
        Procedura importu została zatrzymana.
    </div>
<?php endif; ?>
</div>
</div>