<?php

$title = 'kBudget - Import wyciągu bankowego';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
<div class="span12">

<div class="alert alert-info">
    Serwis umożliwia zaimportowanie transakcji z wyciągu bankowego zapisanego w formacie <b>CSV</b>.<br />
    Wystarczy zalogować się do własnego konta bankowego i wyeksportować historię transakcji do pliku CSV.
    Następnie z poniżeszej listy wybieramy nazwę banku oraz wskazujemy na zapisany plik i naciskamy 'Wyślij',
    aby rozpocząć procedurę importu.
</div>

</div>
</div>

<div class="row">
<div class="span12">

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('import'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<table>
    <tr>
        <td><?php echo $form->get('bank')->getLabel(); ?></td>
        <td><?php echo $this->formElement($form->get('bank')) ?></td>
    </tr>
    <?php
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
            ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
            ->setMessageCloseString('</div></td></tr>')
            ->render($form->get('bank'));
    ?>
    <tr>
        <td><?php echo $form->get('upload_file')->getLabel(); ?></td>
        <td><?php echo $this->formElement($form->get('upload_file')) ?></td>
    </tr>
    <?php
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<tr><td colspan="2"><div class="alert alert-error">')
            ->setMessageSeparatorString('</div></td></tr><tr><td colspan="2"><div class="alert alert-error">')
            ->setMessageCloseString('</div></td></tr>')
            ->render($form->get('upload_file'));
    ?>
    <tr>
        <td colspan="2"><?php echo $this->formSubmit($form->get('submit')); ?></td>
    </tr>
</table>

<?php echo $this->form()->closeTag(); ?>

</div>
</div>