<?php

$title = 'Usuwanie kategorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="span-24">
    
    <div class="error">
        
        <?php if ($EMPTY): ?>
        
        <p>Czy na pewno usunąć kategorię
            '<?php echo $this->escapeHtml($category->c_name); ?>' ?
        </p>
        <?php
        $url = $this->url('user/category/delete', array(
            'cid'     => $this->cid,
        ));
        ?>
        <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="cid" value="<?php echo (int) $category->cid; ?>" />
            <input type="submit" name="del" value="Yes" />
            <input type="submit" name="del" value="No" />
        </div>
        </form> 
        
        <?php else: ?>
        
        <p>
            Wybrana kategoria zawiera transakcje i nie może zostać usunięta.<br />
            Zmień kategorię w odpowiednich transakcjach, a następnie usuń wybraną kategorię ponownie.
        </p>
        <p>
        <a href="<?php echo $this->url('user/category/list');?>">Powrót</a>
        </p>
        
        <?php endif; ?>
        
    </div>

</div>