<?php

$title = 'Usuwanie kategorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="span12">
        
        <?php if ($EMPTY): ?>
        <div class="alert alert-info">
        Czy na pewno usunąć kategorię '<?php echo $this->escapeHtml($category->c_name); ?>' ?
        </div>
        <?php
        $url = $this->url('user/category/delete', array(
            'cid'     => $this->cid,
        ));
        ?>
        <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="cid" value="<?php echo (int) $category->cid; ?>" />
            <input type="submit" name="del" value="Yes" />
            <input type="submit" name="del" value="No" />
        </div>
        </form> 
        <?php else: ?>
        
        <div class="alert alert-error">
            Wybrana kategoria zawiera transakcje i nie może zostać usunięta.<br />
            Zmień kategorię w odpowiednich transakcjach, a następnie usuń wybraną kategorię ponownie.
        </div>
        
        <a href="<?php echo $this->url('user/category/list');?>">Powrót</a>
        
        <?php endif; ?>

    </div>
</div>