<?php

$title = 'kBudget - Edycja kategorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<?php echo $this->configMenu() ?>

<br />

<!-- Formularz kategorii -->
<div class="row">
<div class="span12">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('user/category/edit', array(
                                                                    'cid' => $cid,
                                                                    )));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('cid'));
        echo $this->formHidden($form->get('c_type'));
        echo $this->formRow($form->get('c_name')).'<br />';
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); 
        ?>
</div>
</div>

<div class="row">
<div class="span12">
    <a href="<?php echo $this->url('user/category/list');?>">Powrót</a>
</div>
</div>