<?php

$title = 'kBudget - Konfiguracja kategorii';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<?php echo $this->configMenu() ?>

<br />

<div class="row">
<!-- Kategorie przychodów (lew strona) -->
<div class="span6">
    
    <div class="label label-success">Przychody</div>
    <br /><br />
    
    <!-- Formularz dodania nowej kategorii -->
    Dodaj nową kategorię:
    <?php
    $form = $this->form_profit;
    $form->setAttribute('action', $this->url('user/category/add'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('cid'));
    echo $this->formHidden($form->get('c_type'));
    echo $this->formRow($form->get('c_name')).'<br />';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
    
    <br />
    
    <!-- Lista kategorii -->
    <div>
        <table>
        <tr>
            <th colspan="3" style="text-align: center;">Lista kategorii w przychodach</th>
        </tr>
        <?php foreach ($cat_profit as $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category->c_name);?></td>
            <td>
                <a href="<?php echo $this->url('user/category/edit', array('cid' => $category->cid));?>">Edytuj</a>
            </td>
            <td>
                <a href="<?php echo $this->url('user/category/delete', array('cid' => $category->cid));?>">Usuń</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
    
</div>

<!-- Kategorie wydatków (prawa strona) -->
<div class="span6">
    
    <div class="label label-important">Wydatki</div>
    <br /><br />
    
    <!-- Formularz dodania nowej kategorii -->
    Dodaj nową kategorię:
    <?php
    $form = $this->form_expense;
    $form->setAttribute('action', $this->url('user/category/add'));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('cid'));
    echo $this->formHidden($form->get('c_type'));
    echo $this->formRow($form->get('c_name')).'<br />';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
    
    <br />
    
    <!-- Lista kategorii -->
    <div>
        <table>
        <tr>
            <th colspan="3" style="text-align: center;">Lista kategorii w wydatkach</th>
        </tr>
        <?php foreach ($cat_expense as $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category->c_name);?></td>
            <td>
                <a href="<?php echo $this->url('user/category/edit', array('cid' => $category->cid));?>">Edytuj</a>
            </td>
            <td>
                <a href="<?php echo $this->url('user/category/delete', array('cid' => $category->cid));?>">Usuń</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
    
</div>
</div>
