<?php

$title = 'kBudget - Konfiguracja kategorii';
$this->headTitle($title);

$this->headScript()->prependFile($this->basePath('/js/app/user/categoryList.js'));

$this->headLink()->prependStylesheet($this->basePath('/css/user-categories.css'));

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Linki do poszczególnych ustawień -->
<?php echo $this->configMenu() ?>

<br />

<div class="row">
<!-- Kategorie przychodów (lew strona) -->
<div class="span6">
    
    <div class="label label-success">Przychody</div>
    <div id="catWait" style="display: inline-block;"><img alt="Czekaj..." src="/images/loading.gif"></div>
    <br /><br />
    
    <div class="row">
    
    <!-- Główne kategorie -->
    <div class="span2">
    
    <input type="text" style="width: 115px;" maxlength="50" id="newCatIncome">
    <br />
    <input type="button" value="Dodaj kategorię" id="newCatIncomeButton">
    
    <br /><br />
    
    <select id="catIncomeParent" size="10" style="width: 130px;">
    <?php foreach ($this->cat_profit as $income): ?>
         <option value="<?php echo $income->cid; ?>"><?php echo $income->c_name; ?></option>
    <?php endforeach; ?>
    </select>
    
    <input type="text" style="width: 115px;" maxlength="50" id="editCatIncome">
    <br />
    <input type="button" style="width: 120px;" value="Edytuj kategorię" id="editCatIncomeButton">
    <br />
    <input type="button" style="width: 120px;" value="Usuń kategorię" id="deleteCatIncomeButton">
    
    </div>
    
    <!-- Podkategorie -->
    <div class="span4 subcategories" id="subcategoriesList">
    
    <input type="text" style="width: 115px;" maxlength="50" id="newSubCatIncome">
    <br />
    <input type="button" style="width: 140px;" value="Dodaj podkategorię" id="newSubCatIncomeButton">
    
    <br /><br />
    
    <span id="catIncomeWait"><img alt="Czekaj..." src="/images/loading.gif"></span>
    <span id="catIncomeNoSubcategories">Brak podkategorii</span>
    
    <select id="catIncomeChildren" size="10" style="width: 130px;">
    </select>
    
    <div id="catIncomeEdits">
    <input type="text" style="width: 115px;" maxlength="50" id="editSubCatIncome">
    <br />
    <input type="button" style="width: 150px;" value="Edytuj podkategorię" id="editSubCatIncomeButton">
    <br />
    <input type="button" style="width: 150px;" value="Usuń podkategorię" id="deleteSubCatIncomeButton">
    </div>
    
    </div>
    
    </div>
    
</div>

<!-- Kategorie wydatków (prawa strona) -->
<div class="span6">
    
    <div class="label label-important">Wydatki</div>
    <br /><br />
    
    <div class="row">
    
    <!-- Główne kategorie -->
    <div class="span2">
    
    <input type="text" style="width: 115px;" maxlength="50" id="newCatExpense">
    <br />
    <input type="button" value="Dodaj kategorię" id="newCatExpenseButton">
    
    <br /><br />
    
    <select id="catExpenseParent" size="10" style="width: 130px;">
    <?php foreach ($this->cat_expense as $expense): ?>
         <option value="<?php echo $expense->cid; ?>"><?php echo $expense->c_name; ?></option>
    <?php endforeach; ?>
    </select>
    
    <input type="text" style="width: 115px;" maxlength="50" id="editCatExpense">
    <br />
    <input type="button" style="width: 120px;" value="Edytuj kategorię" id="editCatExpenseButton">
    <br />
    <input type="button" style="width: 120px;" value="Usuń kategorię" id="deleteCatExpenseButton">
    
    </div>
    
    <!-- Podkategorie -->
    <div class="span4 subcategories" id="subcategoriesExpenseList">
    
    <input type="text" style="width: 115px;" maxlength="50" id="newSubCatExpense">
    <br />
    <input type="button" style="width: 140px;" value="Dodaj podkategorię" id="newSubCatExpenseButton">
    
    <br /><br />
    
    <span id="catExpenseWait"><img alt="Czekaj..." src="/images/loading.gif"></span>
    <span id="catExpenseNoSubcategories">Brak podkategorii</span>
    
    <select id="catExpenseChildren" size="10" style="width: 130px;">
    </select>
    
    <div id="catExpenseEdits">
    <input type="text" style="width: 115px;" maxlength="50" id="editSubCatExpense">
    <br />
    <input type="button" style="width: 150px;" value="Edytuj podkategorię" id="editSubCatExpenseButton">
    <br />
    <input type="button" style="width: 150px;" value="Usuń podkategorię" id="deleteSubCatExpenseButton">
    </div>
    
    </div>
    
    </div>
    
</div>
</div>
